#!/usr/bin/env bash
#
# Resolve engine.manifest.json (the hand-edited intent: component versions +
# source URLs) into engine.lock.json (resolved per-arch URLs + SHA256 checksums,
# computed from the ACTUAL downloaded artifacts).
#
# Workflow to upgrade the bundled engine:
#   1. edit engine.manifest.json  -> bump a `version`   (the only manual step)
#   2. npm run engine:lock         -> regenerates engine.lock.json
#   3. npm run engine:fetch        -> pulls the new binaries; commit both files
#
# Never hand-edit checksums. Because this hashes what it downloads (rather than
# trusting an upstream checksum file), the lock records exactly the bytes that
# will ship — review the diff and cross-check against the projects' published
# release checksums before committing.
#
# Usage:
#   scripts/lock-engine.sh           # regenerate engine.lock.json from the manifest
#   scripts/lock-engine.sh --check   # verify the lock is in sync with the manifest
#                                     # (offline; exits non-zero if a relock is due)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MANIFEST="$REPO_ROOT/engine.manifest.json"
LOCKFILE="$REPO_ROOT/engine.lock.json"

need() { command -v "$1" >/dev/null 2>&1 || { echo "error: '$1' is required but not installed" >&2; exit 1; }; }
need jq
[[ -f "$MANIFEST" ]] || { echo "error: manifest not found: $MANIFEST" >&2; exit 1; }

CHECK=0
case "${1:-}" in
  --check) CHECK=1 ;;
  -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
  "") ;;
  *) echo "error: unknown argument '$1'" >&2; exit 1 ;;
esac

manifest() { jq -r "$1" "$MANIFEST"; }
COMPONENTS=()
while IFS= read -r c; do COMPONENTS+=("$c"); done < <(manifest '.dependencies | keys[]')
ARCHES=()
while IFS= read -r a; do ARCHES+=("$a"); done < <(manifest '.arches[]')

# ── --check: fast, offline drift detection (no downloads) ──
# Confirms the lock exists and its version matches the manifest for every
# component + covers every arch. Catches "bumped the manifest, forgot to relock".
if [[ "$CHECK" == 1 ]]; then
  [[ -f "$LOCKFILE" ]] || { echo "✗ engine.lock.json missing — run: npm run engine:lock" >&2; exit 1; }
  drift=0
  for comp in "${COMPONENTS[@]}"; do
    want="$(manifest ".dependencies.\"$comp\".version")"
    have="$(jq -r --arg c "$comp" '.dependencies[$c].version // ""' "$LOCKFILE")"
    if [[ "$want" != "$have" ]]; then
      echo "✗ $comp: manifest=$want lock=${have:-<missing>}" >&2
      drift=1
    fi
    for arch in "${ARCHES[@]}"; do
      sha="$(jq -r --arg c "$comp" --arg a "$arch" '.dependencies[$c].artifacts[$a].sha256 // ""' "$LOCKFILE")"
      if [[ -z "$sha" || "$sha" == "null" ]]; then
        echo "✗ $comp: missing lock entry for arch '$arch'" >&2
        drift=1
      fi
    done
  done
  if [[ "$drift" == 1 ]]; then
    echo "engine.lock.json is out of date — run: npm run engine:lock" >&2
    exit 1
  fi
  echo "✓ engine.lock.json is in sync with engine.manifest.json"
  exit 0
fi

# ── Regenerate the lock from the manifest ──
need curl
need shasum

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# render_url <template> <repo> <version> <arch>
render_url() {
  local u="$1"
  u="${u//\{repo\}/$2}"
  u="${u//\{version\}/$3}"
  u="${u//\{arch\}/$4}"
  printf '%s' "$u"
}

# Build the lock fresh so removed components/arches don't linger.
lock='{
  "_comment": "GENERATED by scripts/lock-engine.sh from engine.manifest.json — do not hand-edit. Resolved URLs + SHA256 (hashed from the downloaded artifacts) for the bundled macOS engine. Consumed by scripts/fetch-engine.sh.",
  "schemaVersion": 1,
  "dependencies": {}
}'

for comp in "${COMPONENTS[@]}"; do
  repo="$(manifest ".dependencies.\"$comp\".repo")"
  version="$(manifest ".dependencies.\"$comp\".version")"
  template="$(manifest ".dependencies.\"$comp\".urlTemplate")"

  echo "▸ ${comp} ${version} (${repo})"
  lock="$(jq --arg c "$comp" --arg v "$version" \
    '.dependencies[$c] = { version: $v, artifacts: {} }' <<<"$lock")"

  for arch in "${ARCHES[@]}"; do
    url="$(render_url "$template" "$repo" "$version" "$arch")"
    echo "    ↓ ${arch}: ${url}"
    if ! curl -fSL --retry 3 -o "$TMP/artifact" "$url"; then
      echo "error: download failed for ${comp} ${version} (${arch})" >&2
      echo "       check the version exists at https://github.com/${repo}/releases" >&2
      exit 1
    fi
    sha="$(shasum -a 256 "$TMP/artifact" | awk '{print $1}')"
    echo "      sha256: ${sha}"
    lock="$(jq --arg c "$comp" --arg a "$arch" --arg u "$url" --arg s "$sha" \
      '.dependencies[$c].artifacts[$a] = { url: $u, sha256: $s }' <<<"$lock")"
  done
done

# Atomic write (temp + rename).
printf '%s\n' "$lock" | jq . > "$TMP/engine.lock.json"
mv "$TMP/engine.lock.json" "$LOCKFILE"

echo
echo "✓ Wrote $LOCKFILE from engine.manifest.json"
echo "  Review the diff, then run: npm run engine:fetch"
